#!/bin/bash

trap 'rm bivouac.lock; exit 0;' EXIT INT TERM;

cd "$(dirname "$(readlink -f "$0")")";

source bivouac.conf

for f in run/*.sh
do
   [ -e "$f" ] || continue
   ./$f &
done


if [[ "$1" == "nomad" ]]; then
    shift;
    ./exe/nomadic.sh $*;
else
    if [[ "$DEVS" == "true" ]]; then
	ruby bin/devs.rb &
    fi
    
    ruby exe/init.rb;
fi
