#!/bin/bash

trap 'rm bivouac.lock; exit 0;' EXIT INT TERM;

cd "$(dirname "$(readlink -f "$0")")";
echo "START `pwd`";
source bivouac.conf

for f in run/*.sh
do
   [ -e "$f" ] || continue
   ./$f &
done


if [[ "$1" == "sync" ]]; then
    ./exe/nomadic.sh install;
else
    if [[ "$DEVS" == "true" ]]; then
	ruby bin/devs.rb &
    fi
    
    ruby exe/init.rb;
fi
