#define WIFI "zyphr"
#define PASS "e13aca76b455"
//#define WIFI "NH-Guest"
//#define PASS "Enjoy your stay!"
#define BROKER "propedicab.com"
#define HUB "BLACKBOX"
#define ID "a92dcfee73e7b29e"
#define BOX "Free%20Range%20Pedicab"
